Rn 0.66.3
rokket-labs/react-native-template-rokket pull request #4
Opened 2021-11-16 19:09 UTC by eliseo3348

2021-11-16 19:22 UTC, tomcastro requested changes

2021-11-16 19:22 UTC, tomcastro commented on template/index.ts
>  }
Creo que es mejor que eliminemos 100% Reactotron. Ya se usa solo Flipper para el debugging en React Native y las últimas veces solo me ha generado problemas. 

Elimina esta parte y el archivo de `ReactotronConfig.ts` porfa.

2021-11-16 19:22 UTC, tomcastro commented on template/package.json
> +    "react-native-reanimated": "^2.2.4",
Aprovecha de actualizar el resto de las librerías, incluidas las devDependencies.

2021-11-16 19:22 UTC, tomcastro commented on template/src/Screens/HomeScreen/index.tsx
> +import Container from '../../Components/Container'
Este import no debería ser relativo si tienes todo lo demás desde src.

2021-11-16 19:22 UTC, tomcastro commented on template/src/Screens/launchesScreen/index.tsx
> +import Container from '../../Components/Container'
Lo mismo acá :)

2021-11-16 20:18 UTC, eliseo3348 commented on template/index.ts
>  }
Eliminado reactotron,  quedó flipper activado

2021-11-16 20:19 UTC, eliseo3348 commented on template/src/Screens/HomeScreen/index.tsx
> +import Container from '../../Components/Container'
arreglado este import

2021-11-16 20:20 UTC, eliseo3348 commented on template/src/Screens/launchesScreen/index.tsx
> +import Container from '../../Components/Container'
aquí también c:

2021-11-16 20:20 UTC, eliseo3348 commented on template/package.json
> +    "react-native-reanimated": "^2.2.4",
Actualizadas el resto de dependencias

2021-11-17 17:48 UTC, tomcastro approved these changes

2021-11-17 17:49 UTC, merged